"""add_tag_group_id_to_schedule

Revision ID: d8eaba7f881e
Revises: ee97307fb363
Create Date: 2026-01-08 22:22:55.004076+09:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd8eaba7f881e'
down_revision: Union[str, None] = 'ee97307fb363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_group_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_schedule_tag_group_id', 'tag_group', ['tag_group_id'], ['id'],
                                    ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_constraint('fk_schedule_tag_group_id', type_='foreignkey')
        batch_op.drop_column('tag_group_id')

    # ### end Alembic commands ###
