"""initial_schema

Revision ID: ee97307fb363
Revises: 
Create Date: 2026-01-08 21:19:16.099525+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee97307fb363'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 기존 데이터가 있으므로 server_default 추가 필요
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_todo', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('tag_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_ratios', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_todo_group', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_group', schema=None) as batch_op:
        batch_op.drop_column('is_todo_group')
        batch_op.drop_column('goal_ratios')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('is_todo')

    # ### end Alembic commands ###
