"""remove_is_todo_group_from_tag_group

Revision ID: f087a3c6cc59
Revises: e5f6a7b8c9d0
Create Date: 2026-03-04 03:11:45.582061+09:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f087a3c6cc59'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_friendship_bidirectional', ['pair_user_id_1', 'pair_user_id_2'])

    with op.batch_alter_table('resource_visibility', schema=None) as batch_op:
        batch_op.alter_column('level',
                              existing_type=sa.VARCHAR(length=8),
                              type_=sa.Enum('private', 'friends', 'selected', 'allowed_emails', 'public',
                                            name='visibilitylevel', native_enum=False),
                              existing_nullable=False)

    with op.batch_alter_table('tag_group', schema=None) as batch_op:
        batch_op.drop_column('is_todo_group')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_todo_group', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))

    with op.batch_alter_table('resource_visibility', schema=None) as batch_op:
        batch_op.alter_column('level',
                              existing_type=sa.Enum('private', 'friends', 'selected', 'allowed_emails', 'public',
                                                    name='visibilitylevel', native_enum=False),
                              type_=sa.VARCHAR(length=8),
                              existing_nullable=False)

    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.drop_constraint('uq_friendship_bidirectional', type_='unique')

    # ### end Alembic commands ###
