"""add_owner_id_to_all_models

Revision ID: cf7d6e2ef7a7
Revises: 1f4bc4f1de04
Create Date: 2026-01-12 03:33:24.487348+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'cf7d6e2ef7a7'
down_revision: Union[str, None] = '1f4bc4f1de04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 기존 데이터를 위해 먼저 nullable=True로 추가 후, 기본값 설정 후 nullable=False로 변경
    default_owner_id = 'legacy-user'
    
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute(f"UPDATE schedule SET owner_id = '{default_owner_id}' WHERE owner_id IS NULL")
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('owner_id', nullable=False)
        batch_op.create_index(batch_op.f('ix_schedule_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('scheduleexception', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute(f"UPDATE scheduleexception SET owner_id = '{default_owner_id}' WHERE owner_id IS NULL")
    with op.batch_alter_table('scheduleexception', schema=None) as batch_op:
        batch_op.alter_column('owner_id', nullable=False)
        batch_op.create_index(batch_op.f('ix_scheduleexception_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute(f"UPDATE tag SET owner_id = '{default_owner_id}' WHERE owner_id IS NULL")
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.alter_column('owner_id', nullable=False)
        batch_op.create_index(batch_op.f('ix_tag_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('tag_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute(f"UPDATE tag_group SET owner_id = '{default_owner_id}' WHERE owner_id IS NULL")
    with op.batch_alter_table('tag_group', schema=None) as batch_op:
        batch_op.alter_column('owner_id', nullable=False)
        batch_op.create_index(batch_op.f('ix_tag_group_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('timersession', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute(f"UPDATE timersession SET owner_id = '{default_owner_id}' WHERE owner_id IS NULL")
    with op.batch_alter_table('timersession', schema=None) as batch_op:
        batch_op.alter_column('owner_id', nullable=False)
        batch_op.create_index(batch_op.f('ix_timersession_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute(f"UPDATE todo SET owner_id = '{default_owner_id}' WHERE owner_id IS NULL")
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('owner_id', nullable=False)
        batch_op.create_index(batch_op.f('ix_todo_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todo_owner_id'))
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('timersession', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timersession_owner_id'))
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('tag_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_group_owner_id'))
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_owner_id'))
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('scheduleexception', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduleexception_owner_id'))
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_owner_id'))
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
